apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: helloji
  ports:
  - protocol: "TCP"
    nodePort: 31080
    port: 5000
    targetPort: 5000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloji
spec:
  selector:
    matchLabels:
      app: helloji
  replicas: 3
  template:
    metadata:
      labels:
        app: helloji
    spec:
      containers:
      - name: hello
        image: vipin2411/webapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
